version: '3.5'

services:

  web:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./code:/code

  php5:
    image: php:5.6-fpm
    volumes:
      - ./code:/code

  php8:
    image: php:8.0-fpm
    volumes:
      - ./code/newdashboard:/code/newdashboard

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1